kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2beta2
metadata:
  name: guestbook-ui-hpa
  namespace: default
spec:
  maxReplicas: 18
  minReplicas: 10
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: guestbook-ui
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 30

    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 30