apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: guestbook-certificate
  namespace: default
spec:
    isCA: true
    secretName: guestbook-tls
    commonName: guestbook.local
    privateKey:
      algorithm: ECDSA
      size: 256
    dnsNames:
        - guestbook.local
    issuerRef:
        name: self-signed-issuer
        kind: ClusterIssuer