apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: guestbook-certificate
  namespace: default
spec:
    secretName: guestbook-tls
    commonName: guestbook.local
    dnsNames:
        - guestbook.local
    issuerRef:
        name: self-signed-issuer
        kind: ClusterIssuer