kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2
metadata:
  name: guestbook-ui-hpa
  namespace: guestbook
spec:
  maxReplicas: 3
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: guestbook-ui
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 30

    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 30