kind: PersistentVolume
apiVersion: v1
metadata:
  name: guestbook-pv
  namespace: default
spec:
  storageClassName: openebs-hostpath
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data
    type: DirectoryOrCreate