kind: PersistentVolume
apiVersion: v1
metadata:
  name: guestbook-pv
  namespace: default
spec:
    storageClassName: openebs-hostpath
    capacity:
        storage: 10Gi
    accessModes:
        - ReadWriteMany
    hostPath:
        path: /mnt/data
        type: Directory