kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: guestbook-pv-claim
  namespace: guestbook
spec:
  storageClassName: openebs-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
