kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: guestbook-pv-claim
  namespace: default
spec:
  storageClassName: openebs-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 0.3Gi
